# Form implementation generated from reading ui file 'dlgAcerca.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgAcerca(object):
    def setupUi(self, dlgAcerca):
        dlgAcerca.setObjectName("dlgAcerca")
        dlgAcerca.resize(363, 221)
        self.gridLayout = QtWidgets.QGridLayout(dlgAcerca)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(parent=dlgAcerca)
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/car_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setCheckable(False)
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)

        self.retranslateUi(dlgAcerca)
        QtCore.QMetaObject.connectSlotsByName(dlgAcerca)

    def retranslateUi(self, dlgAcerca):
        _translate = QtCore.QCoreApplication.translate
        dlgAcerca.setWindowTitle(_translate("dlgAcerca", "Dialog"))
