# Form implementation generated from reading ui file 'dlgSalir.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgSalir(object):
    def setupUi(self, dlgSalir):
        dlgSalir.setObjectName("dlgSalir")
        dlgSalir.resize(311, 174)
        dlgSalir.setModal(True)
        self.imgWarning = QtWidgets.QLabel(parent=dlgSalir)
        self.imgWarning.setGeometry(QtCore.QRect(9, 9, 111, 111))
        self.imgWarning.setText("")
        self.imgWarning.setPixmap(QtGui.QPixmap("img/alert.png"))
        self.imgWarning.setScaledContents(True)
        self.imgWarning.setObjectName("imgWarning")
        self.labelAviso = QtWidgets.QLabel(parent=dlgSalir)
        self.labelAviso.setGeometry(QtCore.QRect(140, 60, 158, 16))
        self.labelAviso.setObjectName("labelAviso")
        self.btnBoxYesNo = QtWidgets.QDialogButtonBox(parent=dlgSalir)
        self.btnBoxYesNo.setGeometry(QtCore.QRect(5, 140, 301, 23))
        self.btnBoxYesNo.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.btnBoxYesNo.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.No|QtWidgets.QDialogButtonBox.StandardButton.Yes)
        self.btnBoxYesNo.setCenterButtons(True)
        self.btnBoxYesNo.setObjectName("btnBoxYesNo")

        self.retranslateUi(dlgSalir)
        self.btnBoxYesNo.accepted.connect(dlgSalir.accept) # type: ignore
        self.btnBoxYesNo.rejected.connect(dlgSalir.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dlgSalir)

    def retranslateUi(self, dlgSalir):
        _translate = QtCore.QCoreApplication.translate
        dlgSalir.setWindowTitle(_translate("dlgSalir", "Aviso"))
        self.labelAviso.setText(_translate("dlgSalir", "¿Está seguro de que quiere salir?"))
