# Form implementation generated from reading ui file 'dlgSalir.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(176, 62)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelTexto = QtWidgets.QLabel(parent=Dialog)
        self.labelTexto.setObjectName("labelTexto")
        self.gridLayout.addWidget(self.labelTexto, 0, 0, 1, 2)
        self.btnSi = QtWidgets.QPushButton(parent=Dialog)
        self.btnSi.setObjectName("btnSi")
        self.gridLayout.addWidget(self.btnSi, 1, 0, 1, 1)
        self.btnNo = QtWidgets.QPushButton(parent=Dialog)
        self.btnNo.setObjectName("btnNo")
        self.gridLayout.addWidget(self.btnNo, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelTexto.setText(_translate("Dialog", "¿Está seguro que desea salir?"))
        self.btnSi.setText(_translate("Dialog", "Sí"))
        self.btnNo.setText(_translate("Dialog", "No"))
