# Form implementation generated from reading ui file 'dlgSalir.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgSalir(object):
    def setupUi(self, dlgSalir):
        dlgSalir.setObjectName("dlgSalir")
        dlgSalir.resize(321, 217)
        dlgSalir.setSizeGripEnabled(False)
        dlgSalir.setModal(True)
        self.formLayout = QtWidgets.QFormLayout(dlgSalir)
        self.formLayout.setObjectName("formLayout")
        self.labelImg = QtWidgets.QLabel(parent=dlgSalir)
        self.labelImg.setText("")
        self.labelImg.setPixmap(QtGui.QPixmap("img/alert.png"))
        self.labelImg.setScaledContents(True)
        self.labelImg.setObjectName("labelImg")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelImg)
        self.btnBox = QtWidgets.QDialogButtonBox(parent=dlgSalir)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBox.sizePolicy().hasHeightForWidth())
        self.btnBox.setSizePolicy(sizePolicy)
        self.btnBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.btnBox.setObjectName("btnBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.btnBox)
        self.labelTexto = QtWidgets.QLabel(parent=dlgSalir)
        self.labelTexto.setObjectName("labelTexto")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.labelTexto)

        self.retranslateUi(dlgSalir)
        QtCore.QMetaObject.connectSlotsByName(dlgSalir)

    def retranslateUi(self, dlgSalir):
        _translate = QtCore.QCoreApplication.translate
        dlgSalir.setWindowTitle(_translate("dlgSalir", "Dialog"))
        self.labelTexto.setText(_translate("dlgSalir", "¿Quieres salir del programa?"))
