package ejercicio1;

/**
 *
 * @author Cristian Bernal Méndez
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAlumno = new javax.swing.JPanel();
        jButtonAnyadirAlumno = new javax.swing.JButton();
        jButtonGuardarAlumno = new javax.swing.JButton();
        jButtonVerAlumno = new javax.swing.JButton();
        jButtonSalvarAlumno = new javax.swing.JButton();
        jPanelModulo = new javax.swing.JPanel();
        jButtonAnyadirModulo = new javax.swing.JButton();
        jButtonGuardarModulo = new javax.swing.JButton();
        jButtonSalvarModulo = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuAlumnos = new javax.swing.JMenu();
        jMenuItemAnyadirAlumno = new javax.swing.JMenuItem();
        jMenuItemVerAlumno = new javax.swing.JMenuItem();
        jMenuItemGuardarAlumno = new javax.swing.JMenuItem();
        jMenuItemSalvarAlumno = new javax.swing.JMenuItem();
        jMenuModulos = new javax.swing.JMenu();
        jMenuItemAnyadirModulo = new javax.swing.JMenuItem();
        jMenuItemGuardarModulo = new javax.swing.JMenuItem();
        jMenuItemSalvarModulo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AcademiaMas");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonAnyadirAlumno.setText("Añadir Alumno");
        jButtonAnyadirAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAnyadirAlumnoMouseClicked(evt);
            }
        });
        jButtonAnyadirAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnyadirAlumnoActionPerformed(evt);
            }
        });

        jButtonGuardarAlumno.setText("Guardar Alumno");

        jButtonVerAlumno.setText("Ver Alumno");

        jButtonSalvarAlumno.setText("Salvar Alumno");

        javax.swing.GroupLayout jPanelAlumnoLayout = new javax.swing.GroupLayout(jPanelAlumno);
        jPanelAlumno.setLayout(jPanelAlumnoLayout);
        jPanelAlumnoLayout.setHorizontalGroup(
            jPanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlumnoLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonAnyadirAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonGuardarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonVerAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSalvarAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(239, Short.MAX_VALUE))
        );
        jPanelAlumnoLayout.setVerticalGroup(
            jPanelAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlumnoLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jButtonAnyadirAlumno)
                .addGap(18, 18, 18)
                .addComponent(jButtonGuardarAlumno)
                .addGap(18, 18, 18)
                .addComponent(jButtonVerAlumno)
                .addGap(18, 18, 18)
                .addComponent(jButtonSalvarAlumno)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 402, 400));
        jPanelAlumno.setVisible(true);

        jButtonAnyadirModulo.setText("Añadir Módulo");
        jButtonAnyadirModulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAnyadirModuloMouseClicked(evt);
            }
        });
        jButtonAnyadirModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnyadirModuloActionPerformed(evt);
            }
        });

        jButtonGuardarModulo.setText("Guardar Módulo");

        jButtonSalvarModulo.setText("Salvar Módulo");

        javax.swing.GroupLayout jPanelModuloLayout = new javax.swing.GroupLayout(jPanelModulo);
        jPanelModulo.setLayout(jPanelModuloLayout);
        jPanelModuloLayout.setHorizontalGroup(
            jPanelModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModuloLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanelModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonAnyadirModulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonGuardarModulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSalvarModulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(240, Short.MAX_VALUE))
        );
        jPanelModuloLayout.setVerticalGroup(
            jPanelModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModuloLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jButtonAnyadirModulo)
                .addGap(18, 18, 18)
                .addComponent(jButtonGuardarModulo)
                .addGap(18, 18, 18)
                .addComponent(jButtonSalvarModulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelModulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 400));
        jPanelModulo.setVisible(false);

        jMenuAlumnos.setText("Alumnos");
        jMenuAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuAlumnosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenuAlumnosMouseEntered(evt);
            }
        });

        jMenuItemAnyadirAlumno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemAnyadirAlumno.setMnemonic('1');
        jMenuItemAnyadirAlumno.setText("Añadir alumno");
        jMenuItemAnyadirAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAnyadirAlumnoActionPerformed(evt);
            }
        });
        jMenuAlumnos.add(jMenuItemAnyadirAlumno);

        jMenuItemVerAlumno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemVerAlumno.setMnemonic('2');
        jMenuItemVerAlumno.setText("Ver alumno");
        jMenuAlumnos.add(jMenuItemVerAlumno);

        jMenuItemGuardarAlumno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemGuardarAlumno.setMnemonic('3');
        jMenuItemGuardarAlumno.setText("Guardar alumno");
        jMenuItemGuardarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGuardarAlumnoActionPerformed(evt);
            }
        });
        jMenuAlumnos.add(jMenuItemGuardarAlumno);

        jMenuItemSalvarAlumno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemSalvarAlumno.setMnemonic('4');
        jMenuItemSalvarAlumno.setText("Salvar alumno");
        jMenuAlumnos.add(jMenuItemSalvarAlumno);

        jMenuBar.add(jMenuAlumnos);

        jMenuModulos.setText("Módulos");
        jMenuModulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenuModulosMouseEntered(evt);
            }
        });

        jMenuItemAnyadirModulo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItemAnyadirModulo.setMnemonic('5');
        jMenuItemAnyadirModulo.setText("Añadir módulo");
        jMenuItemAnyadirModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAnyadirModuloActionPerformed(evt);
            }
        });
        jMenuModulos.add(jMenuItemAnyadirModulo);

        jMenuItemGuardarModulo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItemGuardarModulo.setMnemonic('6');
        jMenuItemGuardarModulo.setText("Guardar módulo");
        jMenuModulos.add(jMenuItemGuardarModulo);

        jMenuItemSalvarModulo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItemSalvarModulo.setMnemonic('7');
        jMenuItemSalvarModulo.setText("Salvar módulo");
        jMenuModulos.add(jMenuItemSalvarModulo);

        jMenuBar.add(jMenuModulos);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAnyadirAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnyadirAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAnyadirAlumnoActionPerformed

    private void jMenuItemAnyadirAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAnyadirAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemAnyadirAlumnoActionPerformed

    private void jMenuItemAnyadirModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAnyadirModuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemAnyadirModuloActionPerformed

    private void jButtonAnyadirAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAnyadirAlumnoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAnyadirAlumnoMouseClicked

    private void jMenuAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAlumnosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuAlumnosMouseClicked

    private void jMenuAlumnosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAlumnosMouseEntered
        // TODO add your handling code here:
        jPanelModulo.setVisible(false);
        jPanelAlumno.setVisible(true);
    }//GEN-LAST:event_jMenuAlumnosMouseEntered

    private void jButtonAnyadirModuloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAnyadirModuloMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAnyadirModuloMouseClicked

    private void jButtonAnyadirModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnyadirModuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAnyadirModuloActionPerformed

    private void jMenuModulosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuModulosMouseEntered
        // TODO add your handling code here:
        jPanelModulo.setVisible(true);
        jPanelAlumno.setVisible(false);
    }//GEN-LAST:event_jMenuModulosMouseEntered

    private void jMenuItemGuardarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGuardarAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemGuardarAlumnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnyadirAlumno;
    private javax.swing.JButton jButtonAnyadirModulo;
    private javax.swing.JButton jButtonGuardarAlumno;
    private javax.swing.JButton jButtonGuardarModulo;
    private javax.swing.JButton jButtonSalvarAlumno;
    private javax.swing.JButton jButtonSalvarModulo;
    private javax.swing.JButton jButtonVerAlumno;
    private javax.swing.JMenu jMenuAlumnos;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemAnyadirAlumno;
    private javax.swing.JMenuItem jMenuItemAnyadirModulo;
    private javax.swing.JMenuItem jMenuItemGuardarAlumno;
    private javax.swing.JMenuItem jMenuItemGuardarModulo;
    private javax.swing.JMenuItem jMenuItemSalvarAlumno;
    private javax.swing.JMenuItem jMenuItemSalvarModulo;
    private javax.swing.JMenuItem jMenuItemVerAlumno;
    private javax.swing.JMenu jMenuModulos;
    private javax.swing.JPanel jPanelAlumno;
    private javax.swing.JPanel jPanelModulo;
    // End of variables declaration//GEN-END:variables
}
